### ISSUE TITLE
How to use it with gulp?

### ISSUE THREAD

**Issue by fabiocaccamo** [lagden/sass-inline-svg-image#1]

**Comment by lagden** [comment]
I suggest you use this: https://github.com/lagden/postcss-inline-base64

This only works with Sass running on Ruby.
So if you want use this with gulp, you must use https://github.com/sindresorhus/gulp-ruby-sass

**Comment by fabiocaccamo** [comment]
I need to dynamically change svg fillcolor, so **postcss-inline-base64** is not enough for my needs.

**Comment by lagden** [comment]
I didn't understand...
Can you show me some code or try explain?

**Comment by fabiocaccamo** [comment]
This is what I would like to do in my .scss:

``` scss
a {
    background-image:svg-url('icon.svg', fillcolor='#000000');

    &:hover {
        background-image:svg-url('icon.svg', fillcolor='#666666');
    }
}
```

Then after building using gulp the generated css should contain the urlencoded svg.
